CREATE DATABASE web3_week12;

CREATE TABLE products (
  id INT AUTO_INCREMENT,
  name VARCHAR(64),
  description VARCHAR(128),
  price INT NOT NULL DEFAULT 0,
  stock INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL,
  PRIMARY KEY (id)
)